import os
from typing import List
import numpy as np
import openai
from openai import OpenAI
from _keys import openai_key

os.environ["OPENAI_API_KEY"] = str(openai_key)
client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])

def embedding_from_string(text: str, model: str = "text-embedding-3-small") -> np.ndarray:
    """Get an embedding as a NumPy vector."""
    resp = client.embeddings.create(model=model, input=text)
    # print("str: ", text, " | embedding: ", np.array(resp.data[0].embedding, dtype=np.float32))
    return np.array(resp.data[0].embedding, dtype=np.float32)


def recommendations_from_strings(
    strings: List[str],
    index_of_source_string: int,
    embeddings: List[str] = [],
    model: str = "text-embedding-3-small",
) -> List[int]:
    """Return nearest neighbors of a given string (including itself first)."""

    # 1) embeddings for all strings
    if len(embeddings) == 0:
        embeddings = [embedding_from_string(s, model=model) for s in strings]

    # 2) source embedding
    query = embeddings[index_of_source_string]

    # 3) cosine *distance* = 1 - cosine similarity
    q_norm = np.linalg.norm(query)
    distances = []
    for e in embeddings:
        denom = q_norm * np.linalg.norm(e)
        sim = float(query @ e / denom) if denom != 0 else 0.0
        distances.append(1.0 - sim)

    # 4) nearest neighbors = smallest distance first
    indices_of_nearest_neighbors = list(np.argsort(distances))

    closest_idx = indices_of_nearest_neighbors[1]
    return [strings[closest_idx], closest_idx, distances[closest_idx]]

    # if distances[closest_idx] <= 0.5:
    #     return strings[closest_idx]
    # return None

def big_test(strings):
    embeddings = [embedding_from_string(s, model="text-embedding-3-small") for s in strings]
    avg = 0
    for idx, s in enumerate(strings):
        res = recommendations_from_strings(strings, idx, embeddings)
        avg += res[2]
        print(s, ": ", res)
    avg /= len(strings)
    print("AVERAGE DISTANCE: ", avg)

def test_embedding():
    strings = [
        "apple",
        "rust",
        "velvet",
        "moonlight",
        "cobblestone",
        "paperclip",
        "toaster",
        "pencil",
        "snow",
        "thunder",
        "cactus",
        "reef",
        "saffron",
        "marble",
        "circuit",
        "pickle",
        "satellite",
        "pyramid",
        "lantern",
        "invoice",
        "stadium",
        "chimney",
        "harbor",
        "jigsaw",
        "cinnamon",
        "umbrella",
        "mustard",
        "helmet",
        "orchard",
        "penguin",
        "fjord",
        "telescope",
        "carnival",
        "microscope",
        "treaty",
        "gravity",
        "shoelace",
        "mushroom",
        "seashell",
        "windmill",
        "brochure",
        "screwdriver",
        "quartz",
        "raven",
        "anvil",
        "luggage",
        "pancake",
        "basil",
        "shampoo",
        "accordion",
        "violin",
        "stethoscope",
        "radiator",
        "dragonfly",
        "dandelion",
        "octopus",
        "sandpaper",
        "notebook",
        "candle",
        "boulder",
        "hinge",
        "doorknob",
        "horizon",
        "tundra",
        "volcano",
        "semaphore",
        "backpack",
        "chalkboard",
        "soybean",
        "tangerine",
        "avalanche",
        "monsoon",
        "hourglass",
        "turnstile",
        "wardrobe",
        "suitcase",
        "hedgehog",
        "armadillo",
        "lighthouse",
        "riverbank",
        "typewriter",
        "teacup",
        "peppermint",
        "spatula",
        "goggles",
        "copper",
        "platinum",
        "mercury",
        "nebula",
        "asteroid",
        "comet",
        "tugboat",
        "sailboat",
        "iceberg",
        "glacier",
        "barnacle",
        "tortoise",
        "gazelle",
        "sardine",
        "parchment",
        "blueprint",
        "toolbox",
        "mortar",
        "pillowcase",
        "thermostat",
        "saxophone",
        "stopwatch",
        "handkerchief",
        "barricade",
        "aqueduct",
        "cathedral",
        "bunkhouse",
        "meadow",
        "canyon",
        "gutter",
        "stapler",
        "keyhole",
        "balcony",
        "tapestry",
        "popsicle",
        "hazelnut",
        "jellyfish",
        "manatee",
        "mongoose",
        "fireplace",
        "skylight",
        "sundial",
        "freight",
        "coupon",
        "microwave",
        "icebox",
        "bathrobe",
        "corridor",
        "sidewalk",
        "handrail",
        "boulevard",
        "headstone",
        "windchime",
        "shoebox",
        "hairpin",
        "filament",
        "wheelbarrow",
        "gondola",
        "wetsuit",
        "snowshoe",
        "velodrome",
        "seasickness",
        "frostbite",
        "aftershock",
        "newsletter",
        "thesaurus",
        "cardboard",
        "bedframe",
        "cutlery",
        "saucepan",
        "turnip",
        "okra",
        "coriander",
        "marmalade",
        "crouton",
        "cheesecake",
        "buttermilk",
        "sourdough",
        "trombone",
        "xylophone",
        "clarinet",
        "metronome",
        "blue jay",
        "sea otter",
        "stone bridge",
        "glass jar",
        "paper boat",
        "gold coin",
        "iron gate",
        "silent engine",
        "broken compass",
        "dusty attic",
        "ancient map",
        "plastic spoon",
        "electric kettle",
        "ceramic mug",
        "wooden plank",
        "velvet curtain",
        "crystal vase",
        "granite slab",
        "midnight train",
        "neon sign",
        "storm cellar",
        "honey jar",
        "sugar cube",
        "salt shaker",
        "pepper grinder",
        "coffee bean",
        "tea leaf",
        "orange peel",
        "lemon wedge",
        "lime zest",
        "cocoa powder",
        "spice rack",
        "kitchen sink",
        "garden hose",
        "water tower",
        "radio tower",
        "signal flare",
        "safety pin",
        "rubber band",
        "sticky note",
        "desk lamp",
        "floor mat",
        "window latch",
        "door hinge",
        "mail slot",
        "ink bottle",
        "paint brush",
        "canvas frame",
        "photo album",
        "ticket stub",
        "train platform",
        "bus stop",
        "parking meter",
        "street vendor",
        "market stall",
        "fruit crate",
        "fish market",
        "bookstore",
        "newsstand",
        "toy chest",
        "sock drawer",
        "coat hanger",
        "shoe rack",
        "laundry basket",
        "soap dish",
        "bath towel",
        "shower curtain",
        "sink faucet",
        "garden gate",
        "flower pot",
        "rose bush",
        "pine cone",
        "oak leaf",
        "maple syrup",
        "birch bark",
        "moss patch",
        "pond water",
        "river delta",
        "ocean current",
        "coral reef",
        "sand dune",
        "cliff edge",
        "cave entrance",
        "mountain pass",
        "forest canopy",
        "prairie grass",
        "desert mirage",
        "arctic ice",
        "tropical storm",
        "quiet harbor",
        "busy harbor",
        "cargo ship",
        "paper lantern",
        "stone lantern",
        "oil lantern",
        "wax candle",
        "scented candle",
        "cold drizzle",
        "warm breeze",
        "sharp shadow",
        "soft echo",
        "steel beam",
        "brick wall",
        "glass ceiling",
        "concrete pillar",
        "painted fence",
        "barbed wire",
        "silk thread",
        "cotton rope",
        "nylon strap",
        "leather belt",
        "wool scarf",
        "silver ring",
        "brass key",
        "copper wire",
        "tin can",
        "aluminum foil",
        "ceramic tile",
        "porcelain plate",
        "stoneware bowl",
        "plastic bin",
        "cardboard box",
        "wood crate",
        "metal locker",
        "office chair",
        "conference table",
        "library card",
        "student badge",
        "passport stamp",
        "boarding pass",
        "hotel keycard",
        "parking permit",
        "lab notebook",
        "safety goggles",
        "glove box",
        "first aid kit",
        "fire extinguisher",
        "smoke alarm",
        "carbon filter",
        "air vent",
        "water valve",
        "pressure gauge",
        "engine block",
        "gearbox",
        "drive shaft",
        "brake pad",
        "spark plug",
        "fuel pump",
        "battery pack",
        "solar panel",
        "wind turbine",
        "hydro dam",
        "power grid",
        "control room",
        "server rack",
        "fiber optic",
        "router",
        "password",
        "encryption key",
        "backup drive",
        "error log",
        "audit trail",
        "access badge",
        "security camera",
        "vault door",
        "bank teller",
        "coffee shop",
        "music hall",
        "movie poster",
        "stage light",
        "spotlight",
        "drumstick",
        "guitar pick",
        "piano bench",
        "sheet music",
        "dance floor",
        "ticket booth",
        "street parade",
        "carnival mask",
        "paper crown",
        "rubber duck",
        "stuffed bear",
        "toy robot",
        "model rocket",
        "kite string",
        "board game",
        "dice cup",
        "playing card",
        "chessboard",
        "checkers piece",
        "snow globe",
        "beach ball",
        "swimming pool",
        "diving board",
        "lifeguard chair",
        "campfire",
        "tent pole",
        "sleeping bag",
        "hiking boot",
        "trail marker",
        "compass rose",
        "topographic map",
        "storm cloud",
        "rain barrel",
        "ice crystal",
        "frozen puddle",
        "morning dew",
        "evening fog",
        "city skyline",
        "country road",
        "farmhouse",
        "grain silo",
        "tractor tire",
        "barn door",
        "hay bale",
        "milk crate",
        "butter churn",
        "wheat field",
        "corn stalk",
        "pumpkin patch",
        "apple orchard",
        "vineyard row",
        "wine bottle",
        "cork stopper",
        "crystal glass",
        "bar counter",
        "menu board",
        "cash register",
        "receipt printer",
        "coin purse",
        "leather wallet",
        "paper receipt",
        "shipping label",
        "packing tape",
        "bubble wrap",
        "fragile sticker",
        "delivery van",
        "loading dock",
        "warehouse aisle",
        "pallet jack",
        "forklift",
        "work glove",
        "hard hat",
        "safety vest",
        "tool belt",
        "measuring tape",
        "spirit level",
        "sledgehammer",
        "paint roller",
        "plaster",
        "cement mixer",
        "blue tarp",
        "rope ladder",
        "fire escape",
        "stairwell",
        "elevator",
        "hallway mirror",
        "doorframe",
        "baseboard",
        "ceiling fan",
        "window shade",
        "curtain rod",
        "potted fern",
        "succulent",
        "bonsai tree",
        "herb garden",
        "basil plant",
        "mint sprig",
        "rosemary twig",
        "thyme bundle",
        "cooking pot",
        "ladle",
        "whisk",
        "rolling pin",
        "cutting board",
        "chef knife",
        "bread loaf",
        "cheese wheel",
        "olive jar",
        "pickle jar",
        "tomato can",
        "soup bowl",
        "rice bag",
        "bean sack",
        "grain bin",
        "spice tin",
        "tea caddy",
        "coffee grinder",
        "espresso cup",
        "napkin holder",
        "table runner",
        "place mat",
        "centerpiece",
        "flower vase",
        "rose petal",
        "lily stem",
        "tulip bulb",
        "sunflower",
        "honeybee",
        "butterfly",
        "ladybug",
        "dragonfly wing",
        "ant hill",
        "bird nest",
        "feather",
        "eggshell",
        "seaglass",
        "driftwood",
        "shell necklace",
        "pearl bead",
        "stone pebble",
        "river stone",
        "lava rock",
        "meteorite",
        "fossil",
        "amber shard",
        "obsidian",
        "jade pendant",
        "opal",
        "diamond",
        "sapphire",
        "emerald",
        "ruby",
        "gold nugget",
        "silver ore",
        "iron ore",
        "coal seam",
        "salt mine",
        "ice cave",
        "volcanic ash",
        "smoke plume",
        "steam vent",
        "hot spring",
        "cool stream",
        "quiet lagoon",
        "stormy sea",
        "tidal pool",
        "wave crest",
        "shipwreck",
        "anchor chain",
        "life raft",
        "compass",
        "nautical chart",
        "signal flag",
        "captain's log",
        "crew cabin",
        "engine room",
        "cargo hold",
        "harbor pilot",
        "customs form",
        "trade route",
        "rail switch",
        "freight car",
        "train whistle",
        "station clock",
        "platform bench",
        "bus ticket",
        "subway map",
        "streetcar",
        "bike lane",
        "skateboard",
        "helmet strap",
        "knee pad",
        "soccer ball",
        "tennis racket",
        "baseball glove",
        "hockey puck",
        "scoreboard",
        "team jersey",
        "coach clipboard",
        "referee whistle",
        "trophy case",
        "medal ribbon",
        "certificate",
        "diploma",
        "textbook",
        "lecture hall",
        "lab coat",
        "microscope slide",
        "test tube",
        "petri dish",
        "culture plate",
        "pipette",
        "centrifuge",
        "chemical flask",
        "oxygen tank",
        "heart monitor",
        "surgical mask",
        "sterile gauze",
        "bandage roll",
        "medicine bottle",
        "pill organizer",
        "clinic hallway",
        "waiting room",
        "reception desk",
        "appointment card",
        "insurance form",
        "patient chart",
        "sticker label",
        "barcode scanner",
        "printer toner",
        "paper tray",
        "ink cartridge",
        "staple remover",
        "binder clip",
        "spiral notebook",
        "index card",
        "sticky tab",
        "highlighter",
        "ballpoint pen",
        "fountain pen",
        "eraser",
        "pencil sharpener",
        "desk organizer",
        "calendar page",
        "hour hand",
        "minute hand",
        "alarm clock",
        "digital clock",
        "time zone",
        "snowstorm",
        "heatwave",
        "sunrise",
        "sunset",
        "eclipse",
        "starlight",
        "milky way",
        "space station",
        "launch pad",
        "rocket engine",
        "capsule",
        "orbital path",
        "gravity well",
    ]
    unique_strings = [
        "apple",
        "rust",
        "velvet",
        "moonlight",
        "cobblestone",
        "paperclip",
        "toaster",
        "pencil",
        "snow",
        "thunder",
        "cactus",
        "reef",
        "saffron",
        "marble",
        "circuit",
        "pickle",
        "satellite",
        "pyramid",
        "lantern",
        "invoice",
        "stadium",
        "chimney",
        "harbor",
        "jigsaw",
        "cinnamon",
        "umbrella",
        "mustard",
        "helmet",
        "orchard",
        "penguin",
        "fjord",
        "telescope",
        "carnival",
        "microscope",
        "treaty",
        "gravity",
        "shoelace",
        "mushroom",
        "seashell",
        "windmill",
        "brochure",
        "screwdriver",
        "quartz",
        "raven",
        "anvil",
        "luggage",
        "pancake",
        "basil",
        "shampoo",
        "accordion",
        "violin",
        "stethoscope",
        "radiator",
        "dragonfly",
        "dandelion",
        "octopus",
        "sandpaper",
        "notebook",
        "candle",
        "boulder",
        "hinge",
        "doorknob",
        "horizon",
        "tundra",
        "volcano",
        "semaphore",
        "backpack",
        "chalkboard",
        "soybean",
        "tangerine",
        "avalanche",
        "monsoon",
        "hourglass",
        "turnstile",
        "wardrobe",
        "suitcase",
        "hedgehog",
        "armadillo",
        "lighthouse",
        "riverbank",
        "typewriter",
        "teacup",
        "peppermint",
        "spatula",
        "goggles",
        "copper",
        "platinum",
        "mercury",
        "nebula",
        "asteroid",
        "comet",
        "tugboat",
        "sailboat",
        "iceberg",
        "glacier",
        "barnacle",
        "tortoise",
        "gazelle",
        "sardine",
        "parchment",
        "blueprint",
        "toolbox",
        "mortar",
        "pillowcase",
        "thermostat",
        "saxophone",
        "stopwatch",
        "handkerchief",
        "barricade",
        "aqueduct",
        "cathedral",
        "bunkhouse",
        "meadow",
        "canyon",
        "gutter",
        "stapler",
        "keyhole",
        "balcony",
        "tapestry",
        "popsicle",
        "hazelnut",
        "jellyfish",
        "manatee",
        "mongoose",
        "fireplace",
        "skylight",
        "sundial",
        "newsletter",
        "thesaurus",
        "cardboard",
        "bedframe",
        "cutlery",
        "saucepan",
        "turnip",
        "okra",
        "coriander",
        "marmalade",
        "crouton",
        "cheesecake",
        "buttermilk",
        "sourdough",
        "trombone",
        "xylophone",
        "clarinet",
        "metronome",
        "blue jay",            # blue, jay (unique)
        "stone bridge",        # stone, bridge (unique)
        "glass jar",           # glass, jar (unique)
        "paper boat",          # paper, boat (unique)
        "gold coin",           # gold, coin (unique)
        "iron gate",           # iron, gate (unique)
        "silent engine",       # silent, engine (unique)
        "broken compass",      # broken, compass (unique)
        "dusty attic",         # dusty, attic (unique)
        "ancient map",         # ancient, map (unique)
        "plastic spoon",       # plastic, spoon (unique)
        "electric kettle",     # electric, kettle (unique)
        "ceramic mug",         # ceramic, mug (unique)
        "wooden plank",        # wooden, plank (unique)
        "crystal vase",        # crystal, vase (unique)
        "granite slab",        # granite, slab (unique)
        "midnight train",      # midnight, train (unique)
        "neon sign",           # neon, sign (unique)
        "storm cellar",        # storm, cellar (unique)
        "honey vat",           # honey, vat (unique)
        "sugar cube",          # sugar, cube (unique)
        "salt shaker",         # salt, shaker (unique)
        "pepper grinder",      # pepper, grinder (unique)
        "coffee bean",         # coffee, bean (unique)
        "tea leaf",            # tea, leaf (unique)
        "orange peel",         # orange, peel (unique)
        "lemon wedge",         # lemon, wedge (unique)
        "lime zest",           # lime, zest (unique)
        "cocoa powder",        # cocoa, powder (unique)
        "spice rack",          # spice, rack (unique)
        "kitchen basin",       # kitchen, basin (unique)
        "garden hose",         # garden, hose (unique)
        "water tower",         # water, tower (unique)
        "radio mast",          # radio, mast (unique)
        "signal flare",        # signal, flare (unique)
        "safety pin",          # safety, pin (unique)
        "rubber band",         # rubber, band (unique)
        "sticky note",         # sticky, note (unique)
        "desk lamp",           # desk, lamp (unique)
        "floor mat",           # floor, mat (unique)
        "window latch",        # window, latch (unique)
        "mail slot",           # mail, slot (unique)
        "ink bottle",          # ink, bottle (unique)
        "paint brush",         # paint, brush (unique)
        "canvas frame",        # canvas, frame (unique)
        "photo album",         # photo, album (unique)
        "ticket stub",         # ticket, stub (unique)
        "bus stop",            # bus, stop (unique)
        "parking meter",       # parking, meter (unique)
        "street vendor",       # street, vendor (unique)
        "market stall",        # market, stall (unique)
        "fruit crate",         # fruit, crate (unique)
        "toy chest",           # toy, chest (unique)
        "sock drawer",         # sock, drawer (unique)
        "coat hanger",         # coat, hanger (unique)
        "shoe shelf",          # shoe, shelf (unique)
        "laundry basket",      # laundry, basket (unique)
        "soap dish",           # soap, dish (unique)
        "bath towel",          # bath, towel (unique)
        "shower curtain",      # shower, curtain (unique)
        "sink faucet",         # sink, faucet (unique)
        "flower pot",          # flower, pot (unique)
        "rose bush",           # rose, bush (unique)
        "pine cone",           # pine, cone (unique)
        "oak twig",            # oak, twig (unique)
        "maple syrup",         # maple, syrup (unique)
        "birch bark",          # birch, bark (unique)
        "moss patch",          # moss, patch (unique)
        "pond waterway",       # pond, waterway (unique)
        "river delta",         # river, delta (unique)
        "ocean current",       # ocean, current (unique)
        "sand dune",           # sand, dune (unique)
        "cliff edge",          # cliff, edge (unique)
        "cave entrance",       # cave, entrance (unique)
        "mountain pass",       # mountain, pass (unique)
        "forest canopy",       # forest, canopy (unique)
        "prairie grass",       # prairie, grass (unique)
        "desert mirage",       # desert, mirage (unique)
        "arctic ice",          # arctic, ice (unique)
        "tropical cyclone",    # tropical, cyclone (unique)
    ]
    unrelated_strings = [
        "gavel",
        "kelp",
        "accordion",
        "sunscreen",
        "asteroid",
        "linoleum",
        "metaphor",
        "tarmac",
        "sourdough",
        "thermostat",
        "yurt",
        "neutron",
        "papyrus",
        "anemone",
        "calculus",
        "saxophone",
        "haystack",
        "molecule",
        "topaz",
        "turnstile",
        "velodrome",
        "parachute",
        "tundra",
        "barcode",
        "kiwi",
        "eclipse",
        "fishhook",
        "candelabra",
        "microchip",
        "monastery",
        "pesticide",
        "ravioli",
        "sandstone",
        "bobsled",
        "quarantine",
        "sunsail",
        "moccasin",
        "manuscript",
        "stalactite",
        "watermark",
        "diploma",
        "tortoise",
        "helium",
        "saffron",
        "catapult",
        "quicksilver",
        "basilisk",
        "tapestry",
        "taxidermy",
        "hazelnut",
        "hourglass",
        "javelin",
        "barometer",
        "cottage",
        "doughnut",
        "avocado",
        "glacier",
        "ballet",
        "wrench",
        "firefly",
        "circuitry",
        "scarecrow",
        "limestone",
        "origami",
        "cyanide",
        "cobalt",
        "marimba",
        "solder",
        "dandelion",
        "bookkeeping",
        "pinnacle",
        "semaphore",
        "magma",
        "skeleton",
        "rhinestone",
        "gondola",
        "tangerine",
        "isotope",
        "harpsichord",
        "casserole",
        "crossbow",
        "vinegar",
        "nebula",
        "cobweb",
        "ukulele",
        "satchel",
        "cathedral",
        "algorithm",
        "fuselage",
        "sunspear",
        "truffle",
        "palisade",
        "radiograph",
        "handrail",
        "hammock",
        "inkwell",
        "snowdrift",
        "parliament",
        "geode",
        "marionette",
        "detergent",
        "stethoscope",
        "carnival",
        "clipboard",
        "hydrangea",
        "pomegranate",
        "sphinx",
        "keystone",
        "polymer",
        "mosaic",
        "thunderclap",
        "sundial",
        "lanyard",
        "icepick",
        "pottery",
        "quill",
        "skylight",
        "monolith",
        "turnip",
        "oxygen",
        "refinery",
        "mandolin",
        "featherweight",
        "saltpeter",
        "aqueduct",
        "typewriter",
        "plankton",
        "detonation",
        "chandelier",
        "hedgehog",
        "velvet",
        "radiator",
        "hologram",
        "honeycomb",
        "mortgage",
        "seismograph",
        "whalebone",
        "tollbooth",
        "necktie",
        "cassette",
        "aardvark",
        "pylon",
        "marathon",
        "soapstone",
        "glyph",
    ]
    
    print("STRINGS TEST")
    print("------------")
    big_test(strings)

    print("\nUNIQUE STRINGS TEST")
    print("-------------------")
    big_test(unique_strings)

    print("\nUNRELATED STRINGS TEST")
    print("----------------------")
    big_test(unrelated_strings)
    

if __name__ == "__main__":
    print("Starting test...")
    test_embedding()
