# Request
geometry_msgs/Pose goal_pose
string pose
---
# Return
geometry_msgs/Pose final_pose
bool success
string message
---
# Feedback
geometry_msgs/Pose current_pose
actionlib_msgs/GoalStatus status